DROP TABLE IF EXISTS `report`;
CREATE TABLE IF NOT EXISTS `report` (
  `uid` VARCHAR(255) NOT NULL, 
  `params` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;